name: Build and Release Binaries

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mapart_helper-linux
            artifact_path: dist/mapart
          - os: windows-latest
            artifact_name: mapart_helper-windows.exe
            artifact_path: dist/mapart.exe
          - os: macos-latest
            artifact_name: mapart_helper-macos-x86
            artifact_path: dist/mapart
          - os: macos-14
            artifact_name: mapart_helper-macos-arm64
            artifact_path: dist/mapart

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy pillow scipy PyQt5 numba

      - name: Build binary
        run: pyinstaller --onefile mapart.py

      - name: Rename binary
        shell: bash
        run: mv ${{ matrix.artifact_path }} ${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: release-files
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          generate_release_notes: true
          files: |
            release-files/*
